language: python
python:
- pypy
- 2.7
- 3.5
install:
- pip install pytest pytest-cov pep8 coveralls;
- pip install -e .
script:
- pytest --cov autotweet --durations=10
- pep8 autotweet tests
- autotweet -h > /dev/null
after_success:
- coveralls
deploy:
  provider: pypi
  user: kjwon15
  password:
    secure: pA4UanWHftEj9gfDqE2dM7yZMXx7baCRo4qzzNs61QqdyKJN/D3/ctV3O3QUt9d5KZGkMsvtOchaKdGoyJSCBJ4PjH70thlTgyiEl5MkOuBVZwDo7Zl1zzKisoy+ZIO7QOLE4TtAfkK48eYTwtGNqM0BN23dMDLDNtNl10OnAfk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Kjwon15/autotweet
