language: python
python:
- pypy
- 2.6
- 2.7
install:
- pip install pytest pytest-cov pep8 coveralls;
- pip install -e .
script:
- pytest --cov autotweet --durations=10
- pep8 autotweet tests
- autotweet -h > /dev/null
after_success:
- coveralls
